//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GadgetHouse.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        public int userId { get; set; }

        [Required(ErrorMessage="name is required.")]
        [Display(Name="Name")]
        public string userName { get; set; }

        [Required(ErrorMessage = "mobile number is required.")]
        [RegularExpression(@"^[0-9]{11}$", ErrorMessage = "valid mobile no is required.")]
        [DataType(DataType.PhoneNumber)]
        [Display(Name = "Mobile")]
        public string Phone { get; set; }

        [Required(ErrorMessage = "address is required.")]
        [Display(Name = "Address")]
        public string userAddress { get; set; }

        [Required(ErrorMessage = "email address is required.")]
        [DataType(DataType.EmailAddress)]
        [Display(Name = "Email")]
        public string userEmail { get; set; }

        [Required(ErrorMessage = "password is required")]
        [MinLength(8, ErrorMessage = "at least 8 characters")]
        [RegularExpression(@"^(?=\D*\d)(?=.*?[a-zA-Z]).*[\W_].*$", ErrorMessage = "must have at least 1 letter, 1 digit & 1 special charecter.")]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string userPassword { get; set; }

        [Required(ErrorMessage = "confirm password is required")]
        [DataType(DataType.Password)]
        [Compare("userPassword", ErrorMessage = "Confirm password is wrong.Type again!")]
        [Display(Name = "Confirm Password")]
        public string ConfirmPassword { get; set; }

    }
}
